import type { Metadata } from "next";
import AOSInit from "@/components/aosinit/index";
import { Manrope } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";

import LenisProvider from "@/components/LenisProvider";

const geistManrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistManrope.variable}} antialiased`}>
        <AOSInit />
        <LenisProvider />
        <Header></Header>
        {children}
      </body>
    </html>
  );
}
